import { Injectable } from "@angular/core";

@Injectable({
    providedIn:'root'
})
export class SharedService{
 patients = [
        {
          "id": 1,
          "uid": "123456",
          "firstName": "Alice",
          "lastName": "Johnson",
          "city": "New York",
          "age": 28,
          "email": "alice@example.com",
          "weight": 135,
          "gender": "Female",
          "contactNumber": "123-456-7890",
          "bloodGroup": "A+"
        },
        {
          "id": 2,
          "uid": "234567",
          "firstName": "Bob",
          "lastName": "Smith",
          "city": "Los Angeles",
          "age": 35,
          "email": "bob@example.com",
          "weight": 175,
          "gender": "Male",
          "contactNumber": "555-123-4567",
          "bloodGroup": "B-"
        },
        {
          "id": 3,
          "uid": "345678",
          "firstName": "Eva",
          "lastName": "Williams",
          "city": "Chicago",
          "age": 22,
          "email": "eva@example.com",
          "weight": 120,
          "gender": "Female",
          "contactNumber": "333-555-7777",
          "bloodGroup": "O+"
        },
        {
          "id": 4,
          "uid": "456789",
          "firstName": "David",
          "lastName": "Brown",
          "city": "Houston",
          "age": 40,
          "email": "david@example.com",
          "weight": 200,
          "gender": "Male",
          "contactNumber": "888-444-2222",
          "bloodGroup": "AB-"
        },
        {
          "id": 5,
          "uid": "567890",
          "firstName": "Sophia",
          "lastName": "Davis",
          "city": "Miami",
          "age": 31,
          "email": "sophia@example.com",
          "weight": 145,
          "gender": "Female",
          "contactNumber": "555-987-6543",
          "bloodGroup": "B+"
        },
        {
          "id": 6,
          "uid": "678901",
          "firstName": "Jack",
          "lastName": "Wilson",
          "city": "San Francisco",
          "age": 29,
          "email": "jack@example.com",
          "weight": 160,
          "gender": "Male",
          "contactNumber": "415-123-4567",
          "bloodGroup": "A-"
        },
        {
          "id": 7,
          "uid": "789012",
          "firstName": "Olivia",
          "lastName": "Taylor",
          "city": "Seattle",
          "age": 27,
          "email": "olivia@example.com",
          "weight": 130,
          "gender": "Female",
          "contactNumber": "206-555-7890",
          "bloodGroup": "O-"
        },
        {
          "id": 8,
          "uid": "890123",
          "firstName": "Noah",
          "lastName": "Miller",
          "city": "Boston",
          "age": 33,
          "email": "noah@example.com",
          "weight": 180,
          "gender": "Male",
          "contactNumber": "617-123-4567",
          "bloodGroup": "A+"
        },
        {
          "id": 9,
          "uid": "901234",
          "firstName": "Ava",
          "lastName": "Martinez",
          "city": "Dallas",
          "age": 26,
          "email": "ava@example.com",
          "weight": 140,
          "gender": "Female",
          "contactNumber": "214-555-7890",
          "bloodGroup": "B+"
        },
        {
          "id": 10,
          "uid": "123450",
          "firstName": "Liam",
          "lastName": "Rodriguez",
          "city": "Denver",
          "age": 30,
          "email": "liam@example.com",
          "weight": 170,
          "gender": "Male",
          "contactNumber": "303-555-1234",
          "bloodGroup": "O-"
        },
        {
          "id": 11,
          "uid": "234561",
          "firstName": "Emma",
          "lastName": "Lopez",
          "city": "Phoenix",
          "age": 24,
          "email": "emma@example.com",
          "weight": 125,
          "gender": "Female",
          "contactNumber": "602-987-6543",
          "bloodGroup": "AB+"
        },
        {
          "id": 12,
          "uid": "345672",
          "firstName": "Mia",
          "lastName": "Garcia",
          "city": "Atlanta",
          "age": 37,
          "email": "mia@example.com",
          "weight": 155,
          "gender": "Female",
          "contactNumber": "404-555-2345",
          "bloodGroup": "B-"
        },
        {
          "id": 13,
          "uid": "456783",
          "firstName": "Lucas",
          "lastName": "Lee",
          "city": "Washington",
          "age": 32,
          "email": "lucas@example.com",
          "weight": 165,
          "gender": "Male",
          "contactNumber": "202-555-6789",
          "bloodGroup": "O+"
        },
        {
          "id": 14,
          "uid": "567894",
          "firstName": "Isabella",
          "lastName": "Scott",
          "city": "Detroit",
          "age": 23,
          "email": "isabella@example.com",
          "weight": 120,
          "gender": "Female",
          "contactNumber": "313-555-9876",
          "bloodGroup": "A-"
        },
        {
          "id": 15,
          "uid": "678905",
          "firstName": "Jackson",
          "lastName": "White",
          "city": "Minneapolis",
          "age": 28,
          "email": "jackson@example.com",
          "weight": 180,
          "gender": "Male",
          "contactNumber": "612-555-3456",
          "bloodGroup": "AB+"
        },
        {
          "id": 16,
          "uid": "789016",
          "firstName": "Emily",
          "lastName": "Harris",
          "city": "Portland",
          "age": 25,
          "email": "emily@example.com",
          "weight": 130,
          "gender": "Female",
          "contactNumber": "503-555-6789",
          "bloodGroup": "O-"
        },
        {
          "id": 17,
          "uid": "890127",
          "firstName": "Daniel",
          "lastName": "Clark",
          "city": "Philadelphia",
          "age": 34,
          "email": "daniel@example.com",
          "weight": 190,
          "gender": "Male",
          "contactNumber": "215-555-1234",
          "bloodGroup": "A+"
        },
        {
          "id": 18,
          "uid": "901238",
          "firstName": "Avery",
          "lastName": "King",
          "city": "Austin",
          "age": 29,
          "email": "avery@example.com",
          "weight": 150,
          "gender": "Female",
          "contactNumber": "512-555-5678",
          "bloodGroup": "B+"
        },
        {
          "id": 19,
          "uid": "123459",
          "firstName": "Logan",
          "lastName": "Green",
          "city": "San Diego",
          "age": 31,
          "email": "logan@example.com",
          "weight": 160,
          "gender": "Male",
          "contactNumber": "619-555-7890",
          "bloodGroup": "O-"
        },
        {
          "id": 20,
          "uid": "234560",
          "firstName": "Harper",
          "lastName": "Perez",
          "city": "Charlotte",
          "age": 26,
          "email": "harper@example.com",
          "weight": 140,
          "gender": "Female",
          "contactNumber": "704-555-2345",
          "bloodGroup": "AB-"
        }
      ];
        
    selectedPatient: any;
   
}